//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNang
    {
        public int IdChucNang { get; set; }
        public string TenChucNang { get; set; }
        public string DieuKhien { get; set; }
        public string PhuongThuc { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    }
}
