//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int IdGroup { get; set; }
        public string TenNhom { get; set; }
        public Nullable<bool> Khoa { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    }
}
